# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - feature-ms-abrahamTosco-mensaje

stages:
  - stage: Build_TestCobertura_PushDocker
    displayName: 'Build_TestCobertura_PushDocker Stage'
    jobs:
      - job: Build_TestCobertura_PushDocker
        pool:
          vmImage: 'ubuntu-latest'
        steps:



          - task: Gradle@3
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'build jacocoTestReport jacocoTestCoverageVerification'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              sonarQubeRunAnalysis: false
              spotBugsAnalysis: false
            displayName: 'Compilacion/Build'

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
              pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
              reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
              failIfCoverageEmpty: true
            displayName: 'Resultado Cobertura Codigo'

          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'aatosco'
              projectKey: 'aatosco_microservicio-spring'
              projectName: 'microservicio-spring'
            displayName: 'SonarCloud Prepare'

          - task: Gradle@3
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'sonarqube'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              sonarQubeRunAnalysis: true
              sqGradlePluginVersionChoice: 'specify'
              sonarQubeGradlePluginVersion: '3.3'
              spotBugsAnalysis: false

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'
            displayName: 'Login_Docker'

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'aatosco/microservicio-spring'
              command: 'build'
              Dockerfile: '**/Dockerfile'
            displayName: 'Build_Imagen_Docker'

          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'aatosco/microservicio-spring'
              command: 'push'
            displayName: 'Push_Imagen_Docker'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build_TestCobertura_PushDocker
    jobs:
      - job: DeployJob
        pool: 'Default'
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'None'
              command: 'create'
              arguments: 'deployment microservicio-spring --image=aatosco/microservicio-spring:72'

#          - script: kubectl port-forward deployment/microservicio-spring 8088:8080 -d