# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature-ms-abrahamTosco-mensaje


pool:
 vmImage: ubuntu-latest

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Compilacion/Build'

- script: |
    echo "El archivo .jar se encuentra en la siguiente ruta: "
    find $(Build.SourcesDirectory) -name "*.jar"
  displayName: 'Mostrar ubicación del archivo .jar'



#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'SonarCloud'
#    organization: 'aatosco'
#    projectKey: 'aatosco_microservicio-spring'
#    projectName: 'microservicio-spring'
#    displayName: 'SonarCloud Prepare'

#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'sonarqube'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: true
#    sqGradlePluginVersionChoice: 'specify'
#    sonarQubeGradlePluginVersion: '3.3'
#    spotBugsAnalysis: false


- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'
  displayName: 'Login_Docker'


- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'aatosco/microservicio-spring'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build_Imagen_Docker'


- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'aatosco/microservicio-spring'
    command: 'push'
  displayName: 'Push_Imagen_Docker'
